name: Pipeline
on:
  push:
    branches:
      - main
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main
      - name: Print text
        run: echo "Text"
      - name: Print text2
        run: echo "Text2"
  transition:
    name: Transition
    runs-on: ubuntu-latest
    steps:
      - uses: atlassian/gajira-login@master
        env:
          # cat: .env
          JIRA_BASE_URL: $(JIRA_BASE_URL)
          # JIRA_USER_EMAIL: $(JIRA_USER_EMAIL)
          JIRA_API_TOKEN: $(JIRA_API_TOKEN)
      - name: Transition
        uses: tuanddd/jira-automate-transition@v1.0.5
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          column-to-move-to-when-review-requested: In Review
          column-to-move-to-when-changes-requested: In Progress
          column-to-move-to-when-merged: QA
          jira-endpoint: https://kostanets.atlassian.net/
          jira-issue-id: FTP-2
