name: Pipeline

on:
  push:
    branches:
      - main

# env:
  # CLIENT_ID: h5MbgGG1Nb95HRxjM2jvDkwdR0Ox1465
  # CLIENT_SECRET: ATOAiuE5CGy0P7o0bKN73iyfhjuVGIABzvlTiBFSIX_q_PcUcwFeZu46oO-uOtguujx82B6CD062
  # CLOUD_INSTANCE_BASE_URL:

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:

      - uses: HighwayThree/jira-upload-build-info@master
        with:
          client-id: 'h5MbgGG1Nb95HRxjM2jvDkwdR0Ox1465'
          # client-id: '${{ secrets.CLIENT_ID }}'
          client-secret: 'ATOAiuE5CGy0P7o0bKN73iyfhjuVGIABzvlTiBFSIX_q_PcUcwFeZu46oO-uOtguujx82B6CD062'
          # client-secret: '${{ secrets.CLIENT_SECRET }}'
          cloud-instance-base-url: '${{ secrets.CLOUD_INSTANCE_BASE_URL }}'
          # cloud-instance-base-url: '${{ secrets.CLOUD_INSTANCE_BASE_URL }}'
          issue-keys: "${{ steps.jira_keys.outputs.jira-keys }}"





      - uses:
          actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Cache node modules
        id: cache-nodemodules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          path: node_modules
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-
      - name: Install Dependencies
        if: steps.cache-nodemodules.outputs.cache-hit != 'true'
        run: |
          npm ci
      - name: Build
        run: |
          npm run build
