name: Pipeline
on:
  push:
    branches:
      - main
jobs:
  transition:
    name: Transition
    runs-on: ubuntu-latest
    steps:
      - name: Jira Integration
        if: ${{ always() }}
        uses: rohit-gohri/jira-ci-cd-integration@v0
        with:
          state: ${{ job.status }}
          environment: staging
          issue: FTP-4, FTP-5 # Comma separated list of issues being deployed/released. You are expected to generate this yourself in a previous step for releases
          jira_instance: kostanets # Subdomain for Jira Cloud
          client_id: ${{ secrets.JIRA_CLIENT_ID }}
          client_secret: ${{ secrets.JIRA_CLIENT_SECRET }}
