name: Pipeline
on:
  push:
    branches:
      - main
jobs:
  text:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Print text
        run: echo "Text"
      - name: Print text2
        run: echo "Text2"
      - name: Jira Ticket Transitioner Action
        uses: tuanddd/jira-automate-transition@v1.0.7-beta
