name: Pipeline
on:
  push:
    branches:
      - main
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@main
      - name: Print text
        run: echo "Text"
      - name: Print text2
        run: echo "Text2"
  transition:
    name: Transition
    runs-on: ubuntu-latest
    steps:
      - name: Env
        uses: atlassian/gajira-login@master
        env:
          JIRA_BASE_URL: https://kostanets.atlassian.net
          JIRA_USER_EMAIL: $(JIRA_USER_EMAIL)
          JIRA_API_TOKEN: $(JIRA_API_TOKEN)
      - name: Jira Ticket Transitioner Action
        uses: tuanddd/jira-automate-transition@v1.0.7-beta
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          column-to-move-to-when-review-requested: In Review
          column-to-move-to-when-changes-requested: In Progress
          column-to-move-to-when-merged: QA
          jira-issue-id: FTP-2
