name: Pipeline

on:
  push:
    branches:
      - main

jobs:
  testing:
    runs-on: ubuntu-latest

    steps:

      - name: Install Dependencies
        if: steps.cache-nodemodules.outputs.cache-hit != 'true'
        run: |
          npm ci

      - name: Build
        run: |
          npm run build
