name: Pipeline
on:
  push:
    branches:
      - main
jobs:
  transition:
    name: Transition
    runs-on: ubuntu-latest
    steps:
      - name: Jira Integration
        if: ${{ always() }}
        uses: rohit-gohri/jira-ci-cd-integration@v0
        with:
          state: ${{ job.status }}
          jira_instance: companyname # Subdomain for Jira Cloud
          client_id: ${{ secrets.JIRA_CLIENT_ID }}
          client_secret: ${{ secrets.JIRA_CLIENT_SECRET }}
          jira-issue-id: FTP-2
