name: Pipeline
on:
  push:
    branches:
      - main
env:
  JIRA_BASE_URL: https://kostanets.atlassian.net/
jobs:
  text:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2



      - name: Checkout
        uses: actions/checkout@master

      - name: Login
        uses: atlassian/gajira-login@master
        env:
          JIRA_BASE_URL: ${{ secrets.JIRA_BASE_URL }}
          JIRA_USER_EMAIL: ${{ secrets.JIRA_USER_EMAIL }}
          JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}

      - name: Find Issue Key
        uses: ./
        with:
          from: commits

      - name: Transition issue
        uses: atlassian/gajira-transition@master
        with:
          issue: ${{ steps.create.outputs.issue }}
          transition: "In Progress"





      - name: Print text
        run: echo "Text"
      - name: Print text2
        run: echo "Text2"
